"""add road route geometry

Revision ID: a003fc229451
Revises: 6c2660d216e8
Create Date: 2026-09-28 20:00:25.036713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a003fc229451'
down_revision = '6c2660d216e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_geometry', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('route_distance_meters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('route_duration_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('route_duration_seconds')
        batch_op.drop_column('route_distance_meters')
        batch_op.drop_column('route_geometry')

    # ### end Alembic commands ###
