"""add hybrid driver dispatch

Revision ID: b325529d9d2e
Revises: 19d90e76768d
Create Date: 2026-09-29 01:25:57.199620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b325529d9d2e'
down_revision = '19d90e76768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_offer_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'driver_id')
    )
    with op.batch_alter_table('driver_offer_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_offer_response_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_offer_response_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatch_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dispatch_deadline_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assignment_method', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_dispatch_deadline_at'), ['dispatch_deadline_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_dispatch_deadline_at'))
        batch_op.drop_column('assignment_method')
        batch_op.drop_column('dispatch_deadline_at')
        batch_op.drop_column('dispatch_started_at')

    with op.batch_alter_table('driver_offer_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_offer_response_order_id'))
        batch_op.drop_index(batch_op.f('ix_driver_offer_response_driver_id'))

    op.drop_table('driver_offer_response')
    # ### end Alembic commands ###
